base/urls.py
from django.urls import path
from .import views

app_name = "base"

urlpatterns = [
    path("", views.homePage, name='home'),
    path('dashboard/<str:pk>/', views.dashboard, name='dashboard'),
    path('contact/', views.contact, name='contact'),
    path('insurance/', views.insurance, name='insurance'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerPage, name='register'),
    path('user-profile/<str:pk>/', views.userProfile, name='profile'),
    path('update-user/', views.updateUser, name='profile-update'),
    path('change-password/', views.changePassword, name='change-password'),
    path('checkout/', views.checkout, name='checkout'),
    
]

daraja/urls.py
from django.urls import path
from .views import InitateSTKPush

app_name="daraja"
urlpatterns = [
    path('',InitateSTKPush.as_view(), name="initatestkpush"),
    
]

insurance/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.urls import re_path as url


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls", namespace="base")),
    path("accounts/", include("allauth.urls")),
    # path('mpesa/', include(mpesa_urls)),
    path('daraja/', include('daraja.urls')),
    # path('daraja/', include('django_daraja.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
import datetime
import uuid
from dateutil.relativedelta import relativedelta
from django.db import models
from django.contrib.auth.models import AbstractUser
from django_resized import ResizedImageField

class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    username = models.CharField(max_length=200, unique=True)
    email = models.EmailField(unique=True, null=True)
    # avatar = models.ImageField(null=True, default='avatar.svg')
    avatar = ResizedImageField(size=[300, 300], default='avatar.svg')
    county = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=13, null=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    USERNAME_FIELD = 'username'

class Contact(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name


class Client(models.Model):
    agent = models.ForeignKey(User, related_name='clients', on_delete= models.DO_NOTHING, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone_imei = models.CharField(max_length=15, unique=True)
    phone_number = models.CharField(max_length=20)
    start_date = models.DateTimeField(auto_now_add=True)
    # end_date = models.DateField()

    def __str__(self):
        return self.email
    @property
    def client_status(self):
        status = 'active'

        created = self.start_date
        period = datetime.timedelta(30*6)
        end_date = created + period

        days = created
        if days < end_date:
            days = created+ datetime.timedelta(days = 1)
            # print(days)
        else:
            status = 'expired'
        
        return status

    def remove_client(self):
        if self.client_status == 'expired':
            self.delete()
        

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Contact, Client, User

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

class InsuranceForm(ModelForm):
    class Meta:
        model = Client
        fields = '__all__'
        exclude = ('start_date', )

class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'phone', 'password1', 'password2']

class Userform(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'phone', 'county']

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.conf import settings
from django.core.mail import send_mail
from django.db.models import Count
from django.views.decorators.csrf import csrf_exempt
from .forms import ContactForm, InsuranceForm, MyUserCreationForm, Userform
from .models import User, Client


def homePage(request):
    return render(request, 'base/home.html')


@login_required(login_url='base:login')
def dashboard(request, pk):
    user = User.objects.get(id=pk)
    client_number = user.clients.all()
    no = client_number.count()
    client = Client.objects.all()
    client_count = client.count()
    sales = client_count * 1000
    mySales = no * 1000
    client_insurance = Client.objects.filter(agent=user)
    
    # 
    # agents = User.objects.annotate(client_count=Count('clients'))
    # client_num = agents.client_count
    

    context = {
        'user' : user,
        'client_count' : client_count,
        'sales' : sales,
        'no' : no,
        'mySales' : mySales,
        'client_number' : client_number,
        
    }
    return render(request, 'base/dashboard.html', context)


def loginPage(request):
    user = request.user
    if request.user.is_authenticated:
        return redirect('base:dashboard', pk=user.id)

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)

        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            messages.info(request, f'You have logged in as {user.username}')
            return redirect('base:dashboard', pk=user.id)
        else:
            messages.error(request, 'Incorrect Username or password')
    return render(request, 'base/pages-login.html')

def logoutUser(request):
    logout(request)
    messages.info(request, 'You have logged out successfuly!')
    return redirect('base:home')

@csrf_exempt
def registerPage(request):
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            messages.success(request, 'Account was created successfuly and you are now logged in')
            return redirect('base:dashboard', pk=user.id)

        else:
            messages.error(request, 'An error occured during registration.')

        context = {
            'form' : form,
        }

    return render(request, 'base/pages-register.html', {'form' : form})


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, 'Your message was sent successfully')
            return redirect ('base:home')
    form = ContactForm()
    context = {
        'form': form,
    }
    return render(request, 'base/contact.html',context)

@login_required(login_url='base:login')
def insurance(request):
    
    if request.method == 'POST':
        form = InsuranceForm(request.POST)
        if form.is_valid():
            form.save()
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            phone_imei = form.cleaned_data['phone_imei']
            # start_date = form.cleaned_data['start_date']
            # end_date = form.cleaned_data['end_date']
            email_subject = 'phone insurance request'
            email_message = first_name + ' ' + last_name + '\n' + email + '\n' + 'phone number: ' + phone_number + '\n' + 'imei number: ' + phone_imei + '\n' 
            # + 'start_date: ' + start_date + '\n' + 'end_date: ' + end_date

            send_mail(email_subject, email_message, settings.CONTACT_EMAIL, settings.ADMIN_EMAIL)
            user = request.user
            messages.success(request, 'You successfully registered a client for insurance')
            return redirect ('base:dashboard', pk=user.id)

    form = InsuranceForm()
    context = {
        'form': form,
    }
    return render(request, 'base/insurance.html', context)

def userProfile(request, pk):
    page = 'profile'
    user = User.objects.get(id=pk)
    context={
        'user' : user,
        'page' : page,
    }

    return render(request, 'base/users-profile.html', context)

@login_required(login_url='base:login')
def updateUser(request):
    page = 'update-user'
    user = request.user
    form = Userform(instance=user)

    if request.method == "POST":
        form = Userform(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, 'You successfully updated your profile')
            return redirect('base:profile', pk=user.id)

    context = {
        'form' : form,
        'page' : page,
    }
    return render(request, 'base/users-profile.html', context)

@login_required(login_url='base:login')
def changePassword(request):
    page = 'change-password'

    if request.method == 'POST':
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        if password1 == password2:
            new_password = make_password(password1)
            request.user.password = new_password
            request.user.save()
            messages.success(request, "You successfully changed your password!")
            user = request.user
            return redirect('base:profile', pk=user.id)

    return render(request, 'base/change_password.html', {'page' : page})


def checkout(request):
    # pay = InitateSTKPush.initiate_mpesa_stk()
    return render(request, 'base/checkout.html')

base/templates/base/checkout.html
{% extends 'main.html' %}
{% load static %}

{% block title %}Checkout{% endblock title %}

{% block content %}


<div class="row">
    <div class="col-md-9">
        <h2 class="section-title text-left">Clients' details go here</h2>


            <div class="row">
                
                
            </div>

            
            <div class="text-center">
            <p class="text-right">
                <a href="{% url 'daraja:initatestkpush' %}" >Checkout</a>
                {% comment %} <input type="submit" class="btn btn-primary" value="Checkout"> {% endcomment %}
                
            </p>
            </div>
        


{% endblock content %}

base/templates/base/insurance.html
{% extends 'main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}insurance{% endblock title %}

{% block content %}

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'base:dashboard' user.id %}" class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/logo.png' %}" alt="">
        <span class="d-none d-lg-block">TAYAz Refurb Tech</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

        <li class="nav-item dropdown">

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{{user.avatar.url}}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{user.username}}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{user.name}}</h6>
              <span>Agent</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'base:profile' user.id %}">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            {% comment %} <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-gear"></i>
                <span>Account Settings</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li> {% endcomment %}

            <li>
              <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                <i class="bi bi-question-circle"></i>
                <span>Need Help?</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'base:logout' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->



			<main class="main-content">
				<div class="breadcrumbs">
					<div class="container">
						<a href="{% url 'base:dashboard' user.id %}">Dashboard</a>
						<span>Insurance</span>
					</div>
				</div>

				<div class="page">
					<div class="container">
						

						<div class="row">
							<div class="col-md-9">
								<h2 class="section-title text-left">Clients' details go here</h2>
								<form action="#" method= "POST" class="contact-form">
									{% csrf_token %}

									<div class="row">
										{{form|crispy}}
										
									</div>

									
									<div class="text-center">
									<p class="text-right">
										<input type="submit" class="btn btn-primary" value="Complete Insurance">
                  </p>
									</div>
								</form>


							</div>
						</div>
					</div>
				</div> <!-- .page -->
			</main>
{% endblock content %}
			

base/templates/base/pages-login.html
{% extends 'main.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}login{% endblock title %}
{% block content %}
  <main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href="{% url 'base:home' %}" class="logo d-flex align-items-center w-auto">
                  <img src="{% static 'assets/img/logo.png' %}" alt="">
                  <span class="d-none d-lg-block">TAYAz Refurb Tech</span>
                </a>
              </div><!-- End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                    <p class="text-center small">Enter your username & password to login</p>
                  </div>

                  <form class="row g-3 needs-validation" method="POST", action="">
                    {% csrf_token %}

                    <div class="col-12">
                      <label for="yourUsername" class="form-label">Username</label>
                      <div class="input-group has-validation">
                        <span class="input-group-text" id="inputGroupPrepend">@</span>
                        <input type="text" name="username" class="form-control" id="yourUsername" required>
                        <div class="invalid-feedback">Please enter your username.</div>
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input type="password" name="password" class="form-control" id="yourPassword" required>
                      <div class="invalid-feedback">Please enter your password!</div>
                    </div>

                    <div class="col-12">
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="remember" value="true" id="rememberMe">
                        <label class="form-check-label" for="rememberMe">Remember me</label>
                      </div>
                    </div>
                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Login</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Don't have account? <a href="{% url 'base:register' %}">Create an account</a></p>
                      <a href=" {% provider_login_url 'google' %} ">Sign in with google</a>
                    </div>
                  </form>

                </div>
              </div>

              <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
                Designed by <a href="https://github/joshwaoti">josh</a>
              </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->
{% endblock content %}

base/templates/base/users-profile.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Profile{% endblock title %}

{% block content %}
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'base:dashboard' user.id %}" class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/logo.png' %}" alt="">
        <span class="d-none d-lg-block">TAYAz Refurb Tech</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

        <li class="nav-item dropdown">

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{{user.avatar.url}}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{user.username}}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{user.name}}</h6>
              <span>Agent</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'base:profile' user.id %}">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            {% comment %} <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-gear"></i>
                <span>Account Settings</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li> {% endcomment %}

            <li>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <i class="bi bi-question-circle"></i>
                <span>Need Help?</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'base:logout' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
    
      <li class="nav-item">
        <a class="nav-link " href="{% url 'base:dashboard' user.id %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->
      

      <li class="nav-heading">Pages</li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'base:insurance' %}">
          <i class="bi bi-card-list"></i>
          <span>Client Insurance</span>
        </a>
      </li><!-- End Client Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'base:profile' user.id %}">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li><!-- End Profile Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="">
          <i class="bi bi-question-circle"></i>
          <span>F.A.Q</span>
        </a>
      </li><!-- End F.A.Q Page Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'base:contact' %}">
          <i class="bi bi-envelope"></i>
          <span>Contact</span>
        </a>
      </li><!-- End Contact Page Nav -->

    </ul>

  </aside><!-- End Sidebar-->

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Profile</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'base:dashboard' user.id %}">Home</a></li>
          <li class="breadcrumb-item">Users</li>
          <li class="breadcrumb-item active">Profile</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->
    {% if page == 'profile' %}
    <section class="section profile">
      <div class="row">
        <div class="col-xl-4">

          <div class="card">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

              <img src="{{user.avatar.url}}" alt="Profile" class="rounded-circle">
              <h2>{{user.name}}</h2>
              <h3>Agent</h3>
              <div class="social-links mt-2">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div>

        </div>

        <div class="col-xl-8">

          <div class="card">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
              <ul class="nav nav-tabs nav-tabs-bordered">

                <li class="nav-item">
                  <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                </li>

                <li class="nav-item">
                  <a href="{% url 'base:change-password' %}">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Edit Profile</button>
                  </a>
                </li>

                <li class="nav-item">
                  <a href=" {% url 'base:change-password' %} ">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password">Change Password</button>
                  </a>
                </li>

              </ul>
              <div class="tab-content pt-2">

                <div class="tab-pane fade show active profile-overview" id="profile-overview">
                  

                  <h5 class="card-title">Profile Details</h5>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">Full Name</div>
                    <div class="col-lg-9 col-md-8">{{user.name}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">username</div>
                    <div class="col-lg-9 col-md-8">{{user.username}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">County</div>
                    <div class="col-lg-9 col-md-8">{{user.county}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Phone</div>
                    <div class="col-lg-9 col-md-8">{{user.phone}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Email</div>
                    <div class="col-lg-9 col-md-8">{{user.email}}</div>
                  </div>

                </div>

                <div class="tab-pane fade profile-edit pt-3" id="profile-edit">
                  {% elif  page == "update-user" %}
                  <!-- Profile Edit Form -->
                  <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% comment %} <div class="row mb-3">
                      <label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Profile Image</label>
                      <div class="col-md-8 col-lg-9">
                        <img src="assets/img/profile-img.jpg" alt="Profile">
                        <div class="pt-2">
                          <a href="#" class="btn btn-primary btn-sm" title="Upload new profile image"><i class="bi bi-upload"></i></a>
                          <a href="#" class="btn btn-danger btn-sm" title="Remove my profile image"><i class="bi bi-trash"></i></a>
                        </div>
                      </div>
                    </div> {% endcomment %}
                    {% for field in form %}
                    <div class="row mb-3">
                      <label for="fullName" class="col-md-4 col-lg-3 col-form-label">{{field.label}}</label>
                      <div class="col-md-8 col-lg-9">
                        {{field}}
                      </div>
                    </div>
                    {% endfor %}

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form><!-- End Profile Edit Form -->
                  
                </div>

                {% comment %} <div class="tab-pane fade pt-3" id="profile-settings">

                  <!-- Settings Form -->
                  <form>

                    <div class="row mb-3">
                      <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Email Notifications</label>
                      <div class="col-md-8 col-lg-9">
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="changesMade" checked>
                          <label class="form-check-label" for="changesMade">
                            Changes made to your account
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="newProducts" checked>
                          <label class="form-check-label" for="newProducts">
                            Information on new products and services
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="proOffers">
                          <label class="form-check-label" for="proOffers">
                            Marketing and promo offers
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="checkbox" id="securityNotify" checked disabled>
                          <label class="form-check-label" for="securityNotify">
                            Security alerts
                          </label>
                        </div>
                      </div>
                    </div>

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form><!-- End settings Form -->
                  
                </div> {% endcomment %}
                {% endif %}
                
                

              </div><!-- End Bordered Tabs -->

            </div>
          </div>

        </div>
      </div>
    </section>
{% endblock content %}